package ba.unsa.etf.rpr.dao;

import ba.unsa.etf.rpr.business.MovieManager;
import ba.unsa.etf.rpr.domain.Movie;
import ba.unsa.etf.rpr.exceptions.MovieException;
import org.apache.commons.lang3.RandomStringUtils;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;
import org.mockito.Mockito;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.mockito.Mockito.when;

public class MovieDaoTest {

    private MovieManager movieManager;
    private Movie movie;


    @BeforeEach
    public void initializeObjectsWeNeed() {
        movieManager = Mockito.mock(MovieManager.class);
        movie = new Movie();
        movie.setName("Inception");
        movie.setId(50);
    }


    @Test
    void add() throws MovieException {
        Mockito.doCallRealMethod().when(movieManager).add(movie);
        MovieException exception = Assertions.assertThrows(MovieException.class, () -> {
            movieManager.add(movie);}, "Can't add movie with ID. ID is autogenerated");
    }
}
